### ISSUE TITLE
Modal js 코드 가독성 관련 PR

### ISSUE THREAD

**Issue by jungpaeng** [jinhyeyeon/basicTodoList#6]
`onChange={({target: {value}}) => this.setState({value})}`
와 같이 작성하는 것이 더 가독성 좋지 않을까요??

_Originally posted by @jungpaeng in https://github.com/jinhyeyeon/basicTodoList/pull/4_

**Comment by jinhyeyeon** [comment]
270affd 수정했습니다 👍
